MVC GarageApp/MVC GarageApp/Controllers/GarageInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_GarageApp.DataAccessLayer;
using MVC_GarageApp.Models;
using PagedList;

namespace MVC_GarageApp.Controllers
{
    public class GarageInfoController : Controller
    {
        private VehicleContext db = new VehicleContext();

        // GET: GarageInfo
        public ActionResult Index(int? page, string searchBy, string search, string sortBy)
        {
            ViewBag.SortOwnerParameter = string.IsNullOrEmpty(sortBy) ? "Owner desc" : "";
            ViewBag.SortRegistrationNumber = sortBy == "RegistrationNumber" ? "RegistrationNumber desc" : "registrationNumber";

            var garageInfo = db.Vehicles.AsQueryable();
            if (searchBy == "RegistrationNumber")
            {
                garageInfo = garageInfo.Where(x => x.RegistrationNumber.Contains(search) || search == null);
            }
            else if (searchBy == "CheckIn")
            {
                garageInfo = garageInfo.Where(x => x.CheckIn.ToString().Contains(search) || search == null);  
            }
            else if (searchBy == "Type")
            {
                garageInfo = garageInfo.Where(x => x.VehicleType.ToString().Contains(search) || search == null);
            }
            else if (searchBy == "Owner")
            {
                garageInfo = garageInfo.Where(x => x.Members.Owner.Contains(search) || search == null);
            }
            else
            {
                garageInfo = garageInfo.Where(x => x.RegistrationNumber.StartsWith(search) || search == null);
            }
            switch (sortBy)
            {
                case "Owner desc":
                    garageInfo = garageInfo.OrderByDescending(x => x.VehicleType);
                    break;
                case "RegistrationNumber":
                    garageInfo = garageInfo.OrderBy(x => x.RegistrationNumber);
                    break;
                case "RegistrationNumber desc":
                    garageInfo = garageInfo.OrderByDescending(x => x.RegistrationNumber);
                    break;
                default:
                    garageInfo = garageInfo.OrderByDescending(x => x.CheckIn);
                    break;
            }
            return View(garageInfo.ToPagedList(page ?? 1, 5));
        }

        // GET: GarageInfo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.Vehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // GET: GarageInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GarageInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RegistrationNumber,Color,Brand,Model,NumberOfWheels,CheckIn,CheckOut")] ParkedVehicle parkedVehicle)
        {
            if (ModelState.IsValid)
            {
                db.Vehicles.Add(parkedVehicle);
                parkedVehicle.CheckIn = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(parkedVehicle);
        }

        // GET: GarageInfo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.Vehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // POST: GarageInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegistrationNumber,Color,Brand,Model,NumberOfWheels,CheckIn,CheckOut")] ParkedVehicle parkedVehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkedVehicle);
        }

        // GET: GarageInfo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.Vehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // POST: GarageInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ParkedVehicle parkedVehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(parkedVehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC GarageApp/MVC GarageApp/Views/GarageInfo/Create.cshtml
@model MVC_GarageApp.Models.ParkedVehicle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ParkedVehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class= "btn btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC GarageApp/MVC GarageApp/Views/GarageInfo/Delete.cshtml
@model MVC_GarageApp.Models.ParkedVehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-info" /> 
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

MVC GarageApp/MVC GarageApp/Views/GarageInfo/Details.cshtml
@model MVC_GarageApp.Models.ParkedVehicle

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id, @class = "btn btn-info" }) 
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-info" })
</p>

MVC GarageApp/MVC GarageApp/Views/GarageInfo/Edit.cshtml
@model MVC_GarageApp.Models.ParkedVehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ParkedVehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null , new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC GarageApp/MVC GarageApp/Views/GarageInfo/GarageInfo.cshtml
@model IPagedList<ParkedVehicle>


    <div class="row">
         @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info" }) 
    </div>
<br />
<fieldset class="row">
    @using (Html.BeginForm("Index", "GarageInfo", FormMethod.Get))
    {
        <p>
            <cite>Search By:</cite><br />
            @Html.RadioButton("SearchBy","Owner",true)<text>Owner&nbsp;</text>
            @Html.RadioButton("SearchBy", "RegistrationNumber")<text>RegNr&nbsp;</text>
            @Html.RadioButton("SearchBy", "VehicleType")<text>Type&nbsp;</text>
            @Html.RadioButton("SearchBy", "CheckIn")<text>CkeckIn&nbsp;</text>
            @Html.TextBox("search", null, new { @class="form-control", placeholder="Search for..."})<br />
            <input type="submit" value="Search" class="btn btn-default" id="btnSearch"/>
        </p>
    }
</fieldset>
<table class="table table-hover table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Members.Owner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehicleType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().RegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CheckIn)
        </th>
        <th></th>
    </tr>
    @if(Model.Count() == 0)
    {
        <tr>
            <td colspan="4">We are sorry no rows match search critiria. Please try again.</td>
        </tr>
    }
    else
    {
        foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Members.Owner)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckIn)
        </td>
        <td>
             @Html.ActionLink("Edit", "Edit",null, new { id = item.Id, @class = "btn btn-info" }) 
             @Html.ActionLink("Details", "Details",null,  new { id = item.Id, @class = "btn btn-info" }) 
             @Html.ActionLink("Delete", "Delete",null, new { id = item.Id, @class = "btn btn-info" })   
        </td>
    </tr>
        }
    }

</table>
<div class="row">
    <div class="text-center">
        @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"] }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
    </div>
</div>

MVC GarageApp/MVC GarageApp/Views/GarageInfo/Index.cshtml
@*@model IPagedList<MemberVehType>

@{
    ViewBag.Title = "GarageInfo";
}

<h2>Garage Information</h2><br />
<fieldset class="row">
    @using (Html.BeginForm("Index", "garageInfo", FormMethod.Get))
    {
        <cite>Search By:</cite><br />
        @Html.RadioButton("SearchBy","RegistrationNumber",true)<text>RegNr&nbsp;</text>
        @Html.RadioButton("SearchBy", "Owner")<text>Owner&nbsp;</text>
        @Html.RadioButton("SearchBy", "VehicleType")<text>Type&nbsp;</text>
        @Html.RadioButton("SearchBy", "CheckIn")<text>Owner&nbsp;</text>
        @Html.TextBox("search", null, new { @class="form-control", placeholder ="Search for..."})<br />
        <input type="submit" value="Search" class="btn btn-info"/>
}
</fieldset><br />
<table class="table table-hover table-responsive table-striped">
    <tr>
        <th>
            @Html.ActionLink("Owner", "Index", new { sortBy = ViewBag.SortOwnerParameter, searchBy= Request.QueryString["searchBy"], search = Request["search"]})
    
        </th>
        <th>
            @Html.ActionLink("RegNr", "Index", new { sortBy = ViewBag.SortRegistrationNumberParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().VehTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CheckIn)
        </th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="7">We are sorry No rows match search critiria. Please try again.</td>
        </tr>
    }
    else
    {
        foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Owner)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckIn)
        </td>
        <td>
             @Html.ActionLink("Details", "Details",null, new { id = item.Id, @class="btn btn-info" })
         </td>
    </tr>
        }
    }
</table>
<div class="row">
    <div class="text-center">
        @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"] }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
    </div>
</div>*@