MVC GarageApp/MVC GarageApp/Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_GarageApp.Models
{
    public class Member
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Please enter your first name.")]
        [DisplayName("First Name")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string FName { get; set; }

        [Required(ErrorMessage ="Please enter your last name.")]
        [DisplayName("Last Name")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string LName { get; set; }

        [Required]
        [Column(TypeName = "datetime2")]
        [DisplayName("Date of Birth YYYY-MM-DD")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage ="Please enter the membership.")]
        [DisplayName("Member Ship")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public int MemberShip { get; set; }

        [Required(ErrorMessage ="Please enter your telephone number.")]
        [DisplayName("Telephone Number")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string TelNumber { get; set; }

        [Required(ErrorMessage ="Please enter your address.")]
        [DisplayName("Address")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string Address { get; set; }

        [Required(ErrorMessage ="Please enter the city.")]
        [DisplayName("City")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string City { get; set; }

        [Required(ErrorMessage ="Please enter your post code.")]
        [DisplayName("Post Code")]
        [DisplayFormat(NullDisplayText ="Undefined")]
        public string Pcode { get; set; }

        [Required(ErrorMessage ="Date is not valid")]
        [Column(TypeName="datetime2")]
        public DateTime StartDate { get; set; }

        public string Owner
        {
            get
            {
                return FName + " " + LName;
            }
        }


        public virtual ICollection<ParkedVehicle> parkedVehicles { get; set; }
    }
}

MVC GarageApp/MVC GarageApp/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_GarageApp.DataAccessLayer;
using MVC_GarageApp.Models;
using PagedList;

namespace MVC_GarageApp.Controllers
{
    public class MembersController : Controller
    {
        private VehicleContext db = new VehicleContext();

        // GET: Members
        public ActionResult Index(int? page,string searchBy, string search, string sortBy)
        {
            ViewBag.SortOwner = string.IsNullOrEmpty(sortBy) ? "Owner desc" : "";
            ViewBag.SortMemberShipParameter = sortBy == "MemberShip" ? "MemberShip desc" : "MemberShip";

            var members = db.Members.AsQueryable();
            if (searchBy == "Owner")
            {
                members = members.Where(x => x.FName.Contains(search) || x.LName.Contains(search) || search == null);
            }
            else if (searchBy == "MemberShip")
            {
                members = members.Where(x => x.MemberShip.ToString().Contains(search) || search == null);
            }
            else if (searchBy == "TelephoneNumber")
            {
                members = members.Where(x => x.TelNumber.Contains(search) || search == null);
            }
            else if (searchBy == "Address")
            {
                members = members.Where(x => x.Address.Contains(search) || search == null);
            }
            else if (searchBy == "City")
            {
                members = members.Where(x => x.City.Contains(search) || search == null);
            }
            else
            {
                members = members.Where(x => x.MemberShip.ToString().StartsWith(search) || search == null);
            }
            switch (sortBy)
            {
                case "Owner desc":
                    members = members.OrderByDescending(x => x.FName);
                    break;
                case "MemberShip":
                    members = members.OrderBy(x => x.MemberShip);
                    break;
                case "MemberShip desc":
                    members = members.OrderByDescending(x => x.MemberShip);
                    break;
                default:
                    members = members.OrderByDescending(x => x.StartDate);
                    break;
            }
            return View(members.ToPagedList(page ?? 1, 5));
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FName,LName,MemberShip,TelNumber,Address,City,Pcode")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                member.StartDate = DateTime.Now;
                db.SaveChanges();
                member.MemberShip = member.Id;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FName,LName,MemberShip,TelNumber,Address,City,Pcode")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC GarageApp/MVC GarageApp/Views/Members/Create.cshtml
@model MVC_GarageApp.Models.Member

@{
    ViewBag.Title = "Register a new member";
}

<h2>Add a new member</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC GarageApp/MVC GarageApp/Views/Members/Delete.cshtml
@model MVC_GarageApp.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberShip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberShip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pcode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-info" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

MVC GarageApp/MVC GarageApp/Views/Members/Details.cshtml
@model MVC_GarageApp.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberShip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberShip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pcode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit",null, new { id = Model.Id, @class = "btn btn-info" }) 
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</p>

MVC GarageApp/MVC GarageApp/Views/Members/Edit.cshtml
@model MVC_GarageApp.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Member Information</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberShip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberShip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberShip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC GarageApp/MVC GarageApp/Views/Members/Index.cshtml
@model IPagedList<Member>

@{
    ViewBag.Title = "Index";
}

<h2>Members</h2>
<div class="row">
     @Html.ActionLink("New Member", "Create", null, new { @class = "btn btn-info" }) 
</div><br />
<fieldset class="row">
    @using (Html.BeginForm("Index", "Members", FormMethod.Get))
    {
            <cite>Search By:</cite><br />
            @Html.RadioButton("SearchBy", "MemberShip", true)<text>MemberShip&nbsp;</text>
            @Html.RadioButton("SearchBy", "Owner")<text>Owner&nbsp;</text>
            @Html.RadioButton("SearchBy","TelephoneNumber")<text>Telephonenumber&nbsp;</text>
            @Html.TextBox("search", null, new { @class = "form-control", placeholder = "Search for..."})<br />
            <input type="submit" value="Search" class="btn btn-info"/>
    }
</fieldset><br />
<div class="row">
    <table class="table table-hover table-responsive table-striped table-inverse">
        <tr>
            <th>
                @Html.ActionLink("Owner", "Index", new { sortBy = ViewBag.SortOwner, searhBy= Request.QueryString["searchBy"], search= Request["search"]})
             </th>
            <th>
                @Html.ActionLink("MemberShip", "Index", new { sortBy = ViewBag.SortMemberShipParameter, searchBy = Request.QueryString["searchBy"], search=Request["search"]})
             </th>
            <th>
                @Html.DisplayNameFor(model => model.First().TelNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().StartDate)
            </th>
            <th></th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="7">We are sorry. No rows match search criteria. Please try again.</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Owner)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MemberShip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TelNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id, @class = "btn btn-info" })
                            
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id, @class = "btn btn-info" })
                    </td>
                </tr>
            }
        }
    </table>
</div>
<div class="row">
    <div class="text-center">
        @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"] }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
    </div>
</div>